import { createElement } from '@lwc/engine-dom';
import DcQ5RealBulk from 'c/dcQ5RealBulk';

describe('c-dc-q-5-real-bulk', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-dc-q-5-real-bulk', {
            is: DcQ5RealBulk
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});